### PR TITLE
fix(examples/urequire): pass rlm through AbortsContains and PanicsContains

### PR DESCRIPTION
**Pull request by thehowl**
## Problem

`ci / examples` has been red on master since #5673 merged (`889405c34`):

```
urequire.gno:84:42: not enough arguments in call to uassert.AbortsContains
urequire.gno:119:42: not enough arguments in call to uassert.PanicsContains
```

Semantic merge conflict: #5673 added `urequire.AbortsContains`/`PanicsContains` wrappers written against the old `uassert` signatures, but `uassert.AbortsContains`/`PanicsContains` gained a `rlm realm` parameter on master in the meantime. Since `urequire/v0` no longer preprocesses, every package importing it fails too (`p/demo/gnorkle/*`, `p/demo/tokens/grc20`, ...).

## Fix

Add the `rlm realm` parameter to both wrappers and pass it through, matching the sibling wrappers in the same file (`AbortsWithMessage`, `PanicsWithMessage`, `NotAborts`, `NotPanics`). #5673 only touched `urequire.gno`, so this covers its full blast radius. No callers of the new wrappers exist yet.

## Verification

- `gno tool transpile -gobuild examples/gno.land/p/nt/urequire/v0` (the failing CI check) passes
- `gno test` passes for `p/nt/urequire/v0` and the previously cascade-failing `p/demo/gnorkle/feeds/static`, `p/demo/gnorkle/storage/simple`, `p/demo/tokens/grc20`
- `gno lint` clean

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by Gno2D2** [comment]
#### 🛠 PR Checks Summary
All **Automated Checks** passed. ✅

##### Manual Checks (for Reviewers):
- [ ] **IGNORE** the bot requirements for this PR (force green CI check)


<details><summary>Read More</summary>

🤖 This bot helps streamline PR reviews by verifying automated checks and providing guidance for contributors and reviewers.

##### ✅ Automated Checks (for Contributors):
 🟢 Maintainers must be able to edit this pull request ([more info](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork))


##### ☑️ Contributor Actions:
1. Fix any issues flagged by automated checks.
2. Follow the Contributor Checklist to ensure your PR is ready for review.
	- Add new tests, or document why they are unnecessary.
	- Provide clear examples/screenshots, if necessary.
	- Update documentation, if required.
	- Ensure no breaking changes, or include `BREAKING CHANGE` notes.
	- Link related issues/PRs, where applicable.

##### ☑️ Reviewer Actions:
1. Complete manual checks for the PR, including the guidelines and additional checks if applicable.

##### 📚 Resources:
- [Report a bug with the bot](https://www.github.com/gnolang/gno/issues/3238).
- [View the bot’s configuration file](https://github.com/gnolang/gno/tree/master/contribs/github-bot/internal/config/config.go).

<details><summary><b>Debug</b></summary><blockquote>
<details><summary><b>Automated Checks</b></summary><blockquote>

<details><summary>Maintainers must be able to edit this pull request (more info)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 And
    ├── 🟢 The base branch matches this pattern: ^master$
    └── 🟢 The pull request was created from a fork (head branch repo: thehowl/gno)

```
### Then
```
🟢 Requirement satisfied
└── 🟢 Maintainer can modify this pull request

```
</blockquote></details>

</blockquote></details>


<details><summary><b>Manual Checks</b></summary><blockquote>

<details><summary>**IGNORE** the bot requirements for this PR (force green CI check)</summary><blockquote>

### If
```
🟢 Condition met
└── 🟢 On every pull request

```
### Can be checked by

- Any user with comment edit permission

</blockquote></details>

</blockquote></details>

</blockquote></details>

</details>
